#!/bin/sh

if [ -n "$nv.boot.default" ]; then
	exit
fi

if [ $bootsource = mmc ]; then
	global.boot.default="bootchooser emmc"
elif [ $bootsource = net ]; then
	global.boot.default="net bootchooser"
else
	global.boot.default="bootchooser sd"
fi
